### ISSUE TITLE
primer usage?

### ISSUE THREAD

**Issue by only1chunts** [DataCurationNetwork/data-primers#35]
Hi, apologies if this is the incorrect forum for this query, please feel free to direct me to the correct place.
I work as a BioCurator for [GigaScience database](http://gigadb.org/) where we assist authors in preparing their data for open sharing to be associated with manuscripts for publication in GigaScience Press journals ([GigaScience](https://gigasciencejournal.com/) and [GigaByte](https://gigabytejournal.com/)).  We are interested to know more about these data-primers to see if they are a suitable mechanism to assist our work and our authors. 
Do those primers already created here get used? If so, how often and who by? 
Is the intention to host a primer for all common data-types or file types? If so, is it restricted to social sciences or any particular fields of study?
Currently, the format of the different primers appears to be a little adhoc with different sub-sections in each, are there plans to unify the layout and content of the primers? I feel that would make it easier for users to navigate between primers more easily.
There also seems to be some primers aimed at the file format level, and some at the data type level, e.g. Twitter as a type of data, vs PDF as a file format. Are there plans to separate the primers based on the target type, and then provide some means of cross-talk? e.g. data from Twitter may include details from the Excel primer.
I have had an attempt at creating a CSV file format data-primer that I am happy to share if you would find it useful?

**Comment by hhkitsune** [comment]
Hi Chris, thanks for your inquiry. 

I believe much of the information you are seeking about this project is included in our Readme, [see here](https://github.com/DataCurationNetwork/data-primers#readme). 

The primary users of these resources are research data curators. The resources were created by data curators working within academic, museum or governmental libraries. These resources offer recommended practices and considerations for the curation of data in selected formats or specialized topic areas. The topics were chosen by the resource creators, most whom had attended one of our three Specialized Data Curation Workshops, generously funded by the Institute of Museum and Library Services. Each of the data curation primers is peer reviewed by members of the [Data Curation Network](https://datacurationnetwork.org), previous workshop attendees, or invited reviewers. These resources are meant to be iterative and may be updated over time to provide additional guidance. A static archival copy of the original version (v 1.0) of each primer that was created adjacent to the workshops may be found here: [Archived Primers](https://conservancy.umn.edu/handle/11299/202810). 

We do have primer creators work from a standard template, so you may notice some common features. However, we allow reasonable deviations of the template that would suit unique information provided for each resource. This allows creators the flexibility to choose a path of investigation into the subject matter that is both suitable to the topic and may leverage expertise of the primer creation group members. Since the primers are iterative, we may adjust their organization and appearance over time to improve cohesion of the collection.

Additional questions may be submitted to the DCN's [comment form](https://datacurationnetwork.org/contact/).
